#!/usr/bin/env bash
# Build the Windows installer (.msi) around an already compiled release binary.
# Two engines share one source of truth (wix/main.wxs): cargo-wix on a Windows
# host builds the full interactive installer; the msitools `wixl` tool elsewhere
# builds the same file tree as a silent package (what `msiexec /a` extracts).
set -euo pipefail

: "${TARGET?the target triple is required}"
: "${VERSION?the version is required}"
: "${PACKAGE_PREFIX?the package prefix is required}"
: "${BINARY?the release binary name is required}"
: "${BUNDLE_NAME?the bundle name is required}"

release_directory="${CARGO_TARGET_DIR:-target}/${TARGET}/release"
mkdir -p "${release_directory}/config"
cp -R config/. "${release_directory}/config/"
package="${PACKAGE_PREFIX}${VERSION}-${TARGET}.msi"
mkdir -p dist
rm -f "dist/${package}" "dist/${package}.sha256" "${package}"

# The digest line must read "<hash>  <file-name>" so `shasum -a 256 -c` passes.
write_digest() {
  local file="$1" name
  name="$(basename "${file}")"
  if command -v shasum >/dev/null 2>&1; then
    (cd "$(dirname "${file}")" && shasum -a 256 "${name}" > "${name}.sha256")
  elif command -v sha256sum >/dev/null 2>&1; then
    (cd "$(dirname "${file}")" && sha256sum "${name}" > "${name}.sha256")
  else
    powershell.exe -NoProfile -Command \
      "(Get-FileHash -Algorithm SHA256 '${file}').Hash.ToLower() + '  ${name}' | Set-Content '${file}.sha256'"
  fi
}

has_cargo_wix() {
  command -v cargo-wix >/dev/null 2>&1 || [ -x "${HOME}/.cargo/bin/cargo-wix" ]
}

if has_cargo_wix; then
  cargo wix --no-build --nocapture -o "${package}" -p baihua-client-gui --target "${TARGET}"
  mv "${package}" dist/
elif command -v wixl >/dev/null 2>&1; then
  # Render the wixl-compatible subset: every Source harvested from main.wxs
  # keeps its relative directory; dialogs, PATH and shortcuts are not wixl's.
  rendered="wixl-installer-${TARGET}.wxs"
  python3 - "${VERSION}" "${release_directory}/${BINARY}" "${BINARY}" "${BUNDLE_NAME}" \
    baihua-client-gui/wix/main.wxs "${rendered}" <<'RENDER'
import pathlib, re, sys, uuid
version, binary_file, binary_name, bundle_name, source_path, output_path = sys.argv[1:7]
def fixed_identifier(seed):
    return str(uuid.uuid5(uuid.NAMESPACE_URL, "https://baihua.app/installer/" + seed))
authoring = pathlib.Path(source_path).read_text(encoding="windows-1252")
upgrade_code = re.search(r"UpgradeCode='([^']+)'", authoring).group(1)
manufacturer = re.search(r"Manufacturer='([^']+)'", authoring).group(1)
files = []
for path in re.findall(r"Source='([^']+)'", authoring):
    normalized = path.replace("\\", "/")
    if normalized.startswith("$(var.") or normalized.startswith("baihua-client-gui/assets"):
        continue
    files.append(tuple(normalized.split("/")))
files.append(("bin", binary_name))
root = {"dirs": {}, "files": []}
for parts in files:
    node = root
    for segment in parts[:-1]:
        node = node["dirs"].setdefault(segment, {"dirs": {}, "files": []})
    node["files"].append(parts)
def safe(text):
    return re.sub(r"[^0-9A-Za-z_]", "_", text)
markup, component_ids, counter = [], [], 0
def emit(node, depth):
    global counter
    pad = " " * depth
    for parts in sorted(node["files"]):
        counter += 1
        identifier = f"component{counter}"
        component_ids.append(identifier)
        source = "/".join(parts) if parts[0] != "bin" or parts[-1] != binary_name else binary_file
        markup.append(f"{pad}<Component Id='{identifier}' Guid='{fixed_identifier(identifier)}'>")
        markup.append(f"{pad}    <File Id='{identifier}File' Source='{source}' KeyPath='yes'/>")
        markup.append(f"{pad}</Component>")
    for segment, child in sorted(node["dirs"].items()):
        markup.append(f"{pad}<Directory Id='{safe(segment)}Folder' Name='{segment}'>")
        emit(child, depth + 2)
        markup.append(f"{pad}</Directory>")
emit(root, 10)
directories = "\n".join(markup)
product_identifier = fixed_identifier("product")
references = "\n".join(f"                <ComponentRef Id='{identifier}'/>" for identifier in component_ids)
document = f"""<?xml version='1.0' encoding='windows-1252'?>
<!-- Generated by scripts/package_windows_installer.sh for the wixl engine. -->
<Wix xmlns='http://schemas.microsoft.com/wix/2006/wi'>
    <Product Id='{product_identifier}' Name='{bundle_name}' Version='{version}' Manufacturer='{manufacturer}'
             Language='1033' Codepage='1252' UpgradeCode='{upgrade_code}'>
        <Package Id='*' Keywords='Installer' Description='{bundle_name} instant messenger'
                 Manufacturer='{manufacturer}' InstallerVersion='200' Languages='1033'
                 Compressed='yes' InstallScope='perMachine' SummaryCodepage='1252'/>
        <Media Id='1' Cabinet='media1.cab' EmbedCab='yes'/>
        <Directory Id='TARGETDIR' Name='SourceDir'>
            <Directory Id='ProgramFilesFolder' Name='PFiles'>
                <Directory Id='APPLICATIONFOLDER' Name='{bundle_name}'>
{directories}
                </Directory>
            </Directory>
        </Directory>
        <Feature Id='Binaries' Title='Application' Level='1' Absent='disallow'>
{references}
        </Feature>
    </Product>
</Wix>
"""
pathlib.Path(output_path).write_text(document, encoding="windows-1252")
RENDER
  wixl -o "${package}" "${rendered}"
  rm -f "${rendered}"
  mv "${package}" dist/
else
  echo "neither cargo-wix (Windows host) nor wixl (msitools) is available" >&2
  echo "on Linux install msitools (apt install wixl); on Windows: cargo install cargo-wix" >&2
  exit 1
fi

write_digest "dist/${package}"
printf "archive=dist/%s\n" "${package}" >> "${GITHUB_ENV:-/dev/null}"
echo "built dist/${package}"
